### ISSUE TITLE
Crash when creating doc on MacOS Sonoma

### ISSUE THREAD

**Issue by Alimuthanaa** [Josdelsan/Proteus#13]
Trying to create a test doc and I the program crashes on my Mac. Any idea? 

<img width="583" alt="Screenshot 2024-09-24 at 16 38 38" src="https://github.com/user-attachments/assets/ffdf0822-d316-48cb-b3a2-69be26372ef7">

[proteus_crash_report-2024-09-24_16-28-35.log](https://github.com/user-attachments/files/17116354/proteus_crash_report-2024-09-24_16-28-35.log)
[proteus_crash_report-2024-09-24_16-33-20.log](https://github.com/user-attachments/files/17116356/proteus_crash_report-2024-09-24_16-33-20.log)
[proteus_crash_report-2024-09-24_16-39-57.log](https://github.com/user-attachments/files/17116357/proteus_crash_report-2024-09-24_16-39-57.log)

**Comment by Josdelsan** [comment]
This issue is related to `setTabsClosable` method of the `QTabWidget` class. In both Linux and Windows, when tabs are marked as closable using the `setTabsClosable` a close button is added to each tab.

Looking at the logs we can confirm that either tab close button is [placed in the left side](https://www.riverbankcomputing.com/static/Docs/PyQt6/api/qtwidgets/qtabbar.html#ButtonPosition) or it is not being created at all.

```
Proteus/proteus/views/components/views_container.py", line 166, in create_component
    self.tabBar().tabButton(0, QTabBar.ButtonPosition.RightSide).hide()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'hide'
```

This will be fix in a hotfix soon. PyQt6 library usually provides methods to access special widgets features regardless the OS but this is not the case. We will do some extended testing apart from the already automated tests in order to find more issue of this nature.
