### ISSUE TITLE
Use convention over configuration for object archetype icons

### ISSUE THREAD

**Issue by amador-duran-toro** [Josdelsan/Proteus#20]
When loading an icon for an object archetype, follow the following sequence:

1. Look for it in profile_name/icons/icons.xml.
2. If not found, search for a class_name.png in profile_name/icons
3. If not found, search for a class_name.png in resources/icons/archetypes
4. If not found, use default icon

In this way, there is no need to declare obvious icons like "paragraph.png" for paragraph objects.

**Comment by Josdelsan** [comment]
Both archetypes and documents (acronym related) icons are now loaded following the sequence:

1. Look for the key in icons.xml (profile and app loaded icons).
2. If not found, search for a class_name.png in profile_name/icons
3. If not found, default icon is used

Searching in resources/icons/archetypes was discarded because storing archetype information outside the profile is not recomended. Eventhough, app icons directory could still store archetype icons if they are configured in the app icons.xml.
